development: &mysql
  adapter: mysql
  database: recipe_dev
  username: root
  password:
  pool: 5
  timeout: 5000
test:
  <<: *mysql
  database: recipe_test
production:
  <<: *mysql
  database: recipe